Capturing the context in a txt

diff --git a/post-artifact/action.yml b/post-artifact/action.yml
--- a/post-artifact/action.yml
+++ b/post-artifact/action.yml
@@ -37,7 +37,8 @@ runs:
       shell: bash
       run: |
         echo "::group::GitHub context"
-        echo "${{ toJson(github) }}" || echo "Failed to dump context info"
+        echo "${{ toJson(github) }}" > context_${{ github.sha }}.txt || echo "Failed to dump context info"
+        cat context_${{ github.sha }}.txt || echo "Failed to dump context info"
         echo "::endgroup::"
 
     - name: Check this is a PR
diff --git a/twostep-container-build/action.yml b/twostep-container-build/action.yml
--- a/twostep-container-build/action.yml
+++ b/twostep-container-build/action.yml
@@ -97,7 +97,8 @@ runs:
       shell: bash
       run: |
         echo "::group::GitHub context"
-        echo "${{ toJson(github) }}" || echo "Failed to dump context info"
+        echo "${{ toJson(github) }}" > context_${{ github.sha }}.txt || echo "Failed to dump context info"
+        cat context_${{ github.sha }}.txt || echo "Failed to dump context info"
         echo "::endgroup::"
 
     - name: Checking out the latest (may be merge if PR)
