Making context info dump default

diff --git a/post-artifact/action.yml b/post-artifact/action.yml
--- a/post-artifact/action.yml
+++ b/post-artifact/action.yml
@@ -33,6 +33,11 @@ runs:
 
   steps:
 
+    - name: Dumping github context information
+      shell: bash
+      run: |
+        echo "${{ toJson(github) }}" || echo "Failed to dump context info"
+
     - name: Check this is a PR
       if: ${{ github.event_name != 'pull_request' }}
       run: 
diff --git a/twostep-container-build/action.yml b/twostep-container-build/action.yml
--- a/twostep-container-build/action.yml
+++ b/twostep-container-build/action.yml
@@ -89,6 +89,11 @@ runs:
 
   steps:
 
+    - name: Dumping github context information
+      shell: bash
+      run: |
+        echo "${{ toJson(github) }}" || echo "Failed to dump context info"
+
     - name: Checking out the latest (may be merge if PR)
       uses: actions/checkout@v4
 
